# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import services_pb2 as services__pb2


class GrpcServicesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExampleCaller = channel.unary_unary(
                '/pb.GrpcServices/ExampleCaller',
                request_serializer=services__pb2.ExampleRequest.SerializeToString,
                response_deserializer=services__pb2.ExampleResponse.FromString,
                )


class GrpcServicesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExampleCaller(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GrpcServicesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExampleCaller': grpc.unary_unary_rpc_method_handler(
                    servicer.ExampleCaller,
                    request_deserializer=services__pb2.ExampleRequest.FromString,
                    response_serializer=services__pb2.ExampleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.GrpcServices', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GrpcServices(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExampleCaller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.GrpcServices/ExampleCaller',
            services__pb2.ExampleRequest.SerializeToString,
            services__pb2.ExampleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
