# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import services_pb2 as services__pb2


class ExampleServicesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Example = channel.unary_unary(
                '/pb.ExampleServices/Example',
                request_serializer=services__pb2.ExampleRequest.SerializeToString,
                response_deserializer=services__pb2.ExampleResponse.FromString,
                )


class ExampleServicesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Example(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExampleServicesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Example': grpc.unary_unary_rpc_method_handler(
                    servicer.Example,
                    request_deserializer=services__pb2.ExampleRequest.FromString,
                    response_serializer=services__pb2.ExampleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.ExampleServices', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ExampleServices(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Example(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.ExampleServices/Example',
            services__pb2.ExampleRequest.SerializeToString,
            services__pb2.ExampleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
