# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\x12\x02pb\"!\n\x0e\x45xampleRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0f\x45xampleResponse\x12\x0b\n\x03res\x18\x01 \x01(\t2H\n\x0cGrpcServices\x12\x38\n\rExampleCaller\x12\x12.pb.ExampleRequest\x1a\x13.pb.ExampleResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXAMPLEREQUEST._serialized_start=22
  _EXAMPLEREQUEST._serialized_end=55
  _EXAMPLERESPONSE._serialized_start=57
  _EXAMPLERESPONSE._serialized_end=87
  _GRPCSERVICES._serialized_start=89
  _GRPCSERVICES._serialized_end=161
# @@protoc_insertion_point(module_scope)
